### ISSUE TITLE
Readme confusion - Mentions Client when it installs tag

### ISSUE THREAD

**Issue by dougwithseismic** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-tag#3]
Not a huge deal but it tripped me for 5 minutes; the installation instructions mention Templates > Client > New. It kept creating a tag (as intended) but I thought I was creating a client.

Great work, thanks for sharing :)

**Comment by angelbt91** [comment]
Hi @dougwithseismic! Sorry for the late reply.

You are absolutely right, my bad. I went too far with copy-pastying the README from the Client template... I'm sorry that made you lost some valuable time. I'll update the README soon.

Again, thanks for the feedback!

**Comment by dougwithseismic** [comment]
No sweat, the setups working really well for us. I'd suggest everyone tries
this route over the ga4 hijack. 👏
