### ISSUE TITLE
Question: What trigger should i made for this tag?

### ISSUE THREAD

**Issue by RemiC2care** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-tag#7]
I use Adsmurai Facebook Conversions API Client with my pixel id and access token. I named it "CAPI".

For the tag i use a custom trigger : Client Name equals CAPI.

But it doesn't work.

I am doing something wrong but i don't know what. Could you help me please?

**Comment by vasfvitor** [comment]
What doesn't work exactly?

Looking at GTM Debug, does the tag fires?

If it fires, what http status does it return?

**Comment by vasfvitor** [comment]
Just to be sure, "it doesn't work" means that the tag isn't firing?

Could you share a screenshot from your trigger?

Here is mine and it's working:
TAG (_é igual a_ means equals):
![image](https://user-images.githubusercontent.com/61759797/166256441-cab43675-aaff-4557-b1c1-e231f3363c58.png)
TRIGGER
![image](https://user-images.githubusercontent.com/61759797/166256544-3977ce85-72cd-4cfe-a3fc-7e11a59d6f49.png)
And the result on Server debug:
![image](https://user-images.githubusercontent.com/61759797/166257115-4d8c1a59-2004-4bde-9846-8cf5b3d69dbf.png)

Hope it helps.

**Comment by RemiC2care** [comment]
Thank you for your help. 

I found my problem, it's in the configuration of the client in the server GTM.

Incoming request url is set to "facebook" but i want i to be blank ( e.g the tooltip) 
![image](https://user-images.githubusercontent.com/56954651/166258507-d3b799a7-1be8-43ca-9c3b-2e4468d7b9a8.png)

But it does not work, it always reset to facebook when leave blank.

So to make it work i had /facebook at the end of the "Your server's URL " in the client side GTM in the tag :
Adsmurai Facebook Pixel & Conversions API (CAPI)

**Comment by angelbt91** [comment]
Thanks @RemiC2care for opening this issue and @vasfvitor for helping :)

Since you already solved your problem, and actually it was on the client template, and you already opened an issue for that [here](https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client/issues/3), I'm going to close this issue and continue on the other one.

Thanks again for getting involved in this project! :)
